services:
  trainer:
    image: vet_trainer_cpu:latest
    build:
      context: ./
      dockerfile: docker/Dockerfile.cpu
    volumes:
      - ./src:/app/src
      - ./models:/app/models
      - ./corpora:/app/corpora
    environment:
      - MODEL_DIR=/app/models # this is the directory where the model will be saved
      - CORPUS_DIR=/app/corpora # this is the directory where to put corpus files